### ISSUE TITLE
What are *valid* keys?

### ISSUE THREAD

**Issue by PalminX** [janpf/ctt#1]
Can you explain what *valid* keys means in the graphs? What would be invalid keys?

**Comment by mh-** [comment]
TEKs / Diagnosis Keys are valid on exactly one day (they have a validity period of max. 24h, ending on 00:00 UTC).
They are not valid on all other days.

**Comment by janpf** [comment]
If you take a look at the plaintext-files below, for example: https://ctt.pfstr.de/plaintext/2020-07-06.txt, you can see that every key has a date it was valid on.
A key is only registered as "infectious" if it was received while it was valid.

Those graphs plot the number of keys that were valid on a given day.

**Comment by PalminX** [comment]
OK, thanks for the clarification, I understand that this is because all TEKs from the last N days are transmitted, but each TEK is only valid for a day.
Closing
