### ISSUE TITLE
Provide a json list of diagnosis key files with hashes

### ISSUE THREAD

**Issue by felixlen** [janpf/ctt#3]
I am about to create a [small application](https://felixlen.github.io/ena_log/) that can match log files of the exposure notification framework and display a nicer report than what Apple/Google are providing. In this report, I am displaying the dates of the diagnosis key file for matches.

As the log file of the exposure notification framework just has the hash of the file inside, I would need a mapping hash -> file. This is [currently hardcoded](https://github.com/felixlen/ena_log/blob/master/src/features/diagnosisKeysSlice.js).

Since you are already maintaining all keys for download and a list, I wondered if you could add a generation of a json object with such a mapping.
Python stub to get the hex representation of a diagnosis key file is as follows:
```
zip_data = zipfile.ZipFile(diagnosis_key_file)
infolist = zip_data.infolist()
with zip_data.open([f for f in infolist if '.bin' in f.filename][0], 'r') as bin_file:
    hash = hashlib.sha256(bin_file.read()).hexdigest()
```

Thanks in advance for consideration and best regards
Felix

**Comment by janpf** [comment]
Thanks for your codesnippet!
I added the mapping under https://ctt.pfstr.de/json/filehashes.json

**Comment by felixlen** [comment]
Thanks a lot, that is exactly what I am looking for.

**Comment by janpf** [comment]
I think you can remove that CORS proxy now, as I might have added headers that allow you to access the mapping directly: 2c7f28b
If it still doesn't work, let me now.

**Comment by felixlen** [comment]
Thanks, works well!

**Comment by felixlen** [comment]
Up to now the list of keys was very useful, so thanks again for providing it! With recent iOS update I noticed however, that the algorithm is used by apple to compute the hashes must have changed:
Currently it worked by computing the sha256 hash of the bin file inside the zip archive.

With a recent exposure log from iOS 14.1, I tried to pinpoint two examples (part of log file):
```
"Files" : [
        {
          "Hash" : "D6C9ADEF176488BB7BCFA9F3A01EB5A9F692817441B777A630A1F74131A03CDF",
          "MatchCount" : 0,
          "KeyCount" : 16122,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-10-23 18:59:04 +0200"
        },
       ...,
        {
          "Hash" : "41444FD9FFAEFDD39A78B11E59DD58EF2146D5F65D39E7607C0E1997712B737F",
          "MatchCount" : 0,
          "KeyCount" : 43934,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-10-23 18:59:03 +0200"
        }]
```
Looking at the key count:
- first example with 16122 keys most likely refers to `2020-10-22.zip`, where the algorithm sha256 on bin file yields `80f50120713fa19c7ba96639c87ed2dab3f770c4ef8546c4f0ed3804c3c0b834`.
- second example with 43934 keys most likely refers to `2020-10-16.zip`, where the algorithm sha256 on bin file yields `256addf082571d25d9db244b85de520aa8822ad12613dea0433dc7bf736d233f`.

Unfortunately Apple is not very helpful, I did not find explanations beyond [detectExposures](https://developer.apple.com/documentation/exposurenotification/enmanager/3586331-detectexposures) on the log files.

I know that this is completely unrelated to your dashboard, but would very much appreciate if we can find out the hashing algorithm and then update the mapping file / create a new mapping file.

Please feel free to ignore this comment and keep the issue closed if you feel that it is too unrelated to your dashboard.

**Comment by janpf** [comment]
I hope I didn't missunderstand the question, but I wasn't able to create either of those two hashes with:
- any hashfunction available to python
- on the daily files or the hourly files
- by hashing the `.bin` file, the `.sig` file, both together, or the published package as a whole

Feel free to suggest additional test cases to the script below:

```python
import hashlib
from typing import Type
import zipfile
from pathlib import Path

hashes_to_be_found = ["D6C9ADEF176488BB7BCFA9F3A01EB5A9F692817441B777A630A1F74131A03CDF", "41444FD9FFAEFDD39A78B11E59DD58EF2146D5F65D39E7607C0E1997712B737F"]
hashes_to_be_found = [h.lower() for h in hashes_to_be_found]


for hash_n in sorted(hashlib.algorithms_available):
    print(f"trying {hash_n}")
    try:
        hash_f: Type[hashlib.sha256] = getattr(hashlib, hash_n)
    except:
        continue
    for key_dir in ["page/keys/", "page/keys_hourly/"]:
        for zfile in sorted(Path(key_dir).iterdir(), reverse=True):
            if ".gitkeep" in str(zfile):
                continue

            # bin file
            zip_data = zipfile.ZipFile(zfile)
            infolist = zip_data.infolist()
            with zip_data.open([f for f in infolist if ".bin" in f.filename][0], "r") as bin_file:
                h = hash_f(bin_file.read())

            try:
                if h.hexdigest() in hashes_to_be_found:
                    print(f"found {h.hexdigest()}:\t{hash_n}\t{zfile.name}\t.bin")
            except:
                pass  # some hash function which takes a parameter for hexdigest

            # sig file
            with zip_data.open([f for f in infolist if ".sig" in f.filename][0], "r") as bin_file:
                h = hash_f(bin_file.read())

            try:
                if h.hexdigest() in hashes_to_be_found:
                    print(f"found {h.hexdigest()}:\t{hash_n}\t{zfile.name}\t.sig")
            except:
                pass  # some hash function which takes a parameter for hexdigest

            # both together
            zip_data = zipfile.ZipFile(zfile)
            infolist = zip_data.infolist()
            h = hash_f()
            for f in infolist:
                with zip_data.open(f, "r") as bin_file:
                    h.update(bin_file.read())

            try:
                if h.hexdigest() in hashes_to_be_found:
                    print(f"found {h.hexdigest()}:\t{hash_n}\t{zfile.name}\tboth together")
            except:
                pass  # some hash function which takes a parameter for hexdigest

            # zip file binary
            with open(zfile, "rb") as f:
                h = hash_f(f.read())

            try:
                if h.hexdigest() in hashes_to_be_found:
                    print(f"found {h.hexdigest()}:\t{hash_n}\t{zfile.name}\twhole zip binary")
            except:
                pass  # some hash function which takes a parameter for hexdigest
```

**Comment by felixlen** [comment]
Thanks a lot for your work. Your question regarding the hourly files was also my first guess and I tried the same thing without success.

I have no idea what iOS is doing internally to compute these hashes from the file, maybe it is related to the cryptographic key of the exposure notification server.

As a workaround until I can figure out what is going on, I was thinking about doing a matching by number of keys in the file and restricting the search to a 14 days window, hoping that these will be unique. Your file `https://ctt.pfstr.de/plots/data.json` would contain everything necessary as datasource. Would you mind allowing cross-origin requests on that file?

**Comment by janpf** [comment]
> Would you mind allowing cross-origin requests on that file?

Done. (I think)


> I have no idea what iOS is doing internally to compute these hashes from the file, maybe it is related to the cryptographic key of the exposure notification server.

If you have a new lead to explore, let me know  :)

**Comment by felixlen** [comment]
> > Would you mind allowing cross-origin requests on that file?
> 
> Done. (I think)
> 
Thanks a lot. It is working, but I realize now that I was confused earlier. I was assuming that `published` in the `plots/data.json` file is the number of keys in that file (this is true by coincidence for `2020-10-22` and created that confusion for me as I blindly generalized). Is the number of keys per file accessible in your data or could you (without a lot of effort on your side) make it available?
 
> > I have no idea what iOS is doing internally to compute these hashes from the file, maybe it is related to the cryptographic key of the exposure notification server.
> 
> If you have a new lead to explore, let me know :)
I will do...

Thanks a lot again and best regards!

**Comment by janpf** [comment]
>  I was confused earlier

whoops, I didn't catch that either as I didn't second guess your idea 🙈 

> this is true by coincidence

It's true for the latest packages, as they are no longer padded.
For all previous files I don't have a `json` file (yet) which tracks the "raw" number of published keys "pre-padding-removal".

> could you make it available?

Sure, I plan to add it over the weekend.

**Comment by janpf** [comment]
I've changed the format of the `filehashes.json`. This way all information is available in a single json file.

Does this work for you?

**Comment by felixlen** [comment]
> I've changed the format of the `filehashes.json`. This way all information is available in a single json file.
> 
> Does this work for you?

Works like a charm, thanks a lot! Although it is a workaround until there is a clearer picture how iOS >= 14.1 is actually calculating the filehash, I am fine with closing.

Thanks again for the super-fast reaction!

**Comment by janpf** [comment]
When you find the hash algorithm, let me know.
