### ISSUE TITLE
Do declining valid keys indicate too-late notification?

### ISSUE THREAD

**Issue by rgerhards** [janpf/ctt#6]
I hope this question is appropriate for the project. I have read that keys are only valid for a given day. Looking at the stats, I notice increasing published keys, but from 9/23 an strongly decreasing number of valid keys. Does that mean keys have been delivered to late (aka "over-stress at health agencies/labs")? I think this discrepancy is important to understand the value of CoronaWarnApp.

Thx!

**Comment by janpf** [comment]
> I notice increasing published keys, but from 9/23 an strongly decreasing number of valid keys.

This is always the case:
for example, 14 days ago, on 09/25 the dashboard looked like this: https://5f6da05b7b19163f5619d4dc--ctt-de.netlify.app/

As every user uploads the keys for (up to) the last 14 days, the final count of valid keys for all days after `currentDate-14 days` is not final and can/will increase.

If somebody who has used the app for the last 14 days, uploads their 14 keys today, they upload a valid key for every day in the last 14 days "retroactively".

> do *increasing invalid* keys indicate too-late notification?

A decrease in valid keys does not equal an increase in invalid keys.
There are no invalid keys. The word valid just refers to the day a key was active/valid on (see #1).

>Does that mean keys have been delivered to late (aka "over-stress at health agencies/labs")?

No.

> I hope this question is appropriate for the project.

Of course! I hope this explanation helps.

**Comment by rgerhards** [comment]
Thx for the swift reply.

> If somebody who has used the app for the last 14 days, uploads their 14 keys today, they upload a valid key for every day in the last 14 days "retroactively".

I see, thx for the clarification.

I think this is very vital information. I suggest to add a link to some explanatory text and maybe reconsider the wording. I assume `valid` is a well-defined term in this context, so it cannot be reworded. Iif so, I suggest to put it into quotes like `"valid"`.

Reasoning:
While this page may not be meant for display to the general public, it may happen (I was short of twitter-posting the link actually). I know that certain folks would immediately step up and say "see, the corona app has only invalid data for the past two weeks, it does not work at all" (you probably know what I mean). I understand this is a political, non-tech concern. But these things can be vital ATM, unfortunately.

I know that https://micb25.github.io/dka/ has easier to understand information, but I also know that "certain folks" prefer to post links to presentations that seem to back their opinion, especially given the fact that many casual observers do not read more than a couple of words these days..

Thx again for all the work and dedication! It is great that the positive growth is visible (the link should really be better known).

**Comment by janpf** [comment]
> I think this is very vital information.

I agree!

> I suggest to add a link to some explanatory text and maybe reconsider the wording. I assume `valid` is a well-defined term in this context, so it cannot be reworded. Iif so, I suggest to put it into quotes like `"valid"`.

I tried that by linking to "What are valid keys?" below every graph that uses valid keys, but I guess it gets easily overlooked.

> add a link to some explanatory text

I'm going to link this issue as well below every graph using valid keys.

> you probably know what I mean

I do.

> has easier to understand information

I'm always open to suggestions and pull requests ;)

**Comment by rgerhards** [comment]
> I tried that by linking to "What are valid keys?" below every graph that uses valid keys, but I guess it gets easily overlooked.

actually, I read that issue, but not having a deep understanding of the system as whole, I seem I have misinterpreted it (still not 100% sure TBH). The mistook the term "Diagnosis Key" with a key that was diagnosed positive. Thus also the initial thought about "over-stressed labs".

**Comment by janpf** [comment]
> mistook the term "Diagnosis Key" with a key that was diagnosed positive.

They kind of are. Your phone generates "Temporary Exposure Keys (TEK)", which to my understanding become "Diagnosis Keys", once you upload them to the server. They are technically identical, they just get renamed by getting tested positive.

Once this gets implemented, you could likely estimate how long the labs took to return the results:
https://github.com/mh-/diagnosis-keys/issues/12
https://github.com/corona-warn-app/cwa-app-ios/pull/1151
