### ISSUE TITLE
Charts: date overflow

### ISSUE THREAD

**Issue by stefanb** [janpf/ctt#9]
Happy new year! 🎉 
With first data for the 2021-01-01 the charts started plotting the 2021 data as if it was for 2020, disregarding the year:
![image](https://user-images.githubusercontent.com/319826/103453365-83560900-4cd9-11eb-8f27-a338fe18ac57.png)

**Comment by janpf** [comment]
Happy New Year! 🎆
Thanks for notifying me and including a pullrequest. That was a bug I was certainly not expecting to happen!
